# => Create a new Protection Job for a set of VMs given in the inventory
# =>
---
  - hosts: localhost
    # => Please change these variables to connect
    # => to your Cohesity Cluster
    vars:
        var_cohesity_server: 10.2.33.137
        var_cohesity_admin: admin
        var_validate_certs: False
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      # => Manage VMware
      - name: Create new Protection Job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: "{{ var_cohesity_server }}"
          cohesity_admin: "{{ var_cohesity_admin }}"
          cohesity_password: "{{ var_cohesity_password }}"
          cohesity_validate_certs: "{{ var_validate_certs }}"
          cohesity_protection:
              state: present
              job_name: "{{ job_name }}"
              policy: "{{ policy_name }}"
              sources:
                - endpoint: "{{ endpoint }}"
              environment: "VMware"
              include:
                - "{{ vm_name }}"
        tags: [ 'cohesity', 'sources', 'register', 'vmware' ]

      - name: Start On-Demand Protection Job Execution
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: "{{ var_cohesity_server }}"
          cohesity_admin: "{{ var_cohesity_admin }}"
          cohesity_password: "{{ var_cohesity_password }}"
          cohesity_validate_certs: "{{ var_validate_certs }}"
          cohesity_protection:
              state: started
              job_name: "{{ job_name }}"
              environment: "VMware"
        tags: [ 'cohesity', 'sources', 'started', 'vmware' ]