---
  - hosts: localhost
    # => Please change these variables to connect
    # => to your Cohesity Cluster
    vars:
        var_cohesity_server: 10.2.33.137
        var_cohesity_admin: admin
        var_validate_certs: False
        var_vcenter_username: administrator
    gather_facts: no
    roles:
        - cohesity.cohesity_ansible_role
    tasks:
      - name: Configure Cohesity Protection Source on VMware vCenter Host
        include_role:
            name: cohesity.cohesity_ansible_role
            tasks_from: source
        vars:
            cohesity_server: "{{ var_cohesity_server }}"
            cohesity_admin: "{{ var_cohesity_admin }}"
            cohesity_password: "{{ var_cohesity_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_source:
                state: present
                endpoint: "{{var_vcenter_server }}"
                environment: "VMware"
                vmware_type: "VCenter"
                source_username: "{{ var_vcenter_username }}"
                source_password: "{{ var_vcenter_password }}"
        tags: [ 'cohesity', 'sources', 'register', 'vmware' ]